---
graphics: yes
name: Juan David
surname: Leongómez Peña
position: Profesor Asociado
address: "PhD University of Stirling · MSc University of Liverpool"
phone: (+57) 319 407 7102
email: "juanleongomez@gmail.com"
www: jdleongomez.info
date: "`r Sys.setlocale('LC_TIME','Spanish');format(Sys.Date(),'%d de %B de %Y')`"
header-includes: \usepackage{multicol}
  \usepackage{colortbl}
  \usepackage{orcidlink}
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/apa-cv.csl"
headcolor: 333333
docname: Referencias Académicas
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

pkgs <- c('vitae' ,'here' ,'tinytex' ,'tibble' ,'glue' ,'rmarkdown' ,'dplyr', 'readr' ,'yaml')
xfun::pkg_attach2(pkgs)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data sctructure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative Filepaths
             ,'readr'     # Data Loading
             ,'tidyverse' # Needed for bind_rows and whatever
             ,'scholar'   # Updating publications from google scholar
             ,'kableExtra'# Adding technicalskills table
            )
library(magrittr)
# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
lapply(packages, library, character.only = TRUE) %>%
  invisible()
```

\vspace{4mm}
\begin{tcolorbox}[enhanced,
        on line, 
        boxsep=4pt, left=0pt,right=0pt,top=0pt,bottom=0pt,
        colframe=white,colback=black]
  
\color{white}
\begin{LARGE}\begin{center}
Documento 6. \textbf{Referencias Académicas}
\end{center}\end{LARGE}
\end{tcolorbox}

```{r referencias}
ezpickr::pick("referencias.xlsx") |>
  tidyr::fill(-why) |>
  vitae::detailed_entries(what, when, with, where, why,
                          .protect = FALSE)
```